### ISSUE TITLE
Fix connection type

### ISSUE THREAD

**Issue by colemancda** [PureSwift/BluetoothLinux#12]
Getting `New BREDR connection` in `L2CAPServerTest` and `GATTServerTest`.
Should be `LowEnergyPublic`. Could be related to endianness on ARM.

**Comment by kabanishe23** [comment]
I am facing this on ARMv6 (Raspberry Pi Zero W)

**Comment by kabanishe23** [comment]
@colemancda It seems like I found the issue. In your `GATTServerTest ` you're not calling `startListening()` of `L2CAPSocket`, but it's required to start listen before calling `waitForConnection()`

**Comment by colemancda** [comment]
The issue was due to passing `0x02` instead of `0x01` for `l2_bdaddr_type` when creating the L2CAP socket.
