### ISSUE TITLE
ECDH secure pairing

### ISSUE THREAD

**Issue by ashishguru1986** [PureSwift/BluetoothLinux#15]
http://blog.bluetooth.com/everything-you-always-wanted-to-know-about-bluetooth-security-in-bluetooth-4-2/

**Adding LE Secure Connections to Your Products**
You need to upgrade the security manager in your Bluetooth stack to support the following:

Generation and management of ECDH keys
LE Secure Connection pairing requests
Generation of ECDH keys and Long Term Keys (LTK)
Generation and exchange of cross transport keys

Does **BluetoothLinux**  stack implements ECDH ?

**Comment by colemancda** [comment]
No it does not. In my own products I use my own encryption technology.
