### ISSUE TITLE
Is it possible to create BLE Device compatible with iOS (not iBeacon)?

### ISSUE THREAD

**Issue by kabanishe23** [PureSwift/BluetoothLinux#22]
I was able to create such device using modified code from `GATTServerTest`. I can connect to the device but I can't see any services and characteristics in `LightBlue Explorer`. `waitForConnection()` keep everything blocked after connecting. Could you give an example for this?

**Comment by colemancda** [comment]
Here are 2 examples:
https://github.com/colemancda/Lock
https://github.com/colemancda/DemoPeripheral
